name: ParcelPlugin
version: '1.0-SNAPSHOT'
main: com.mody.parcelplugin.ParcelPlugin
api-version: '1.20'
description: System zarządzania parcelami w Minecraft
commands:
  parcel:
    description: Główna komenda do zarządzania parcelami
    usage: |
      /parcel stworz <nazwa> <gracz> <x1> <y1> <z1> <x2> <y2> <z2>
      /parcel dodaj <nazwa> <gracz>
      /parcel zniszcz <nazwa>
      /parcel usun <nazwa> <gracz>
permissions:
  parcel.create:
    description: Uprawnienie do tworzenia parceli
    default: op