name: GamblerPlugin
version: '${project.version}'
main: com.mody.gamblerplugin.GamblerPlugin
api-version: '1.20'
commands:
  kubki:
    description: Tworzy NPC do gry w kubki
    usage: /kubki stworz npc <x> <y> <z>
depend: [Citizens]  # Wymagany Citizens